services:
  - type: web
    name: itcollege-testing
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn testcollege.wsgi --workers 4 --timeout 120"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: itcollege-db
          property: connectionString

databases:
  - name: itcollege-db
    databaseName: testcollege
    plan: free
