# Generated by Django 6.0.2 on 2026-05-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('school', models.CharField(max_length=300, verbose_name='Школа / Учебное заведение')),
                ('grade', models.CharField(choices=[('9', '9 класс'), ('11', '11 класс')], max_length=2, verbose_name='Класс')),
                ('pin', models.CharField(max_length=14, unique=True, verbose_name='ПИН')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала теста')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения теста')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Тест завершён')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Номер вопроса в предмете')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['subject__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для выбора')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='test_pdfs/', verbose_name='PDF-документ теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вариант теста',
                'verbose_name_plural': 'Варианты теста',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='testing.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Общий балл (из 60)')),
                ('english_score', models.PositiveIntegerField(default=0, verbose_name='Английский язык (из 20)')),
                ('math_score', models.PositiveIntegerField(default=0, verbose_name='Математика (из 20)')),
                ('russian_score', models.PositiveIntegerField(default=0, verbose_name='Русский язык (из 20)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('abiturient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='testing.abiturient', verbose_name='Абитуриент')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testvariant', verbose_name='Вариант теста'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='test_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testing.testvariant', verbose_name='Выбранный вариант теста'),
        ),
        migrations.CreateModel(
            name='AbiturientAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ответ верный')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.abiturient', verbose_name='Абитуриент')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.answeroption', verbose_name='Выбранный вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abiturient_answers', to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ абитуриента',
                'verbose_name_plural': 'Ответы абитуриентов',
                'ordering': ['question__subject__order', 'question__order'],
                'unique_together': {('abiturient', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('variant', 'subject', 'order')},
        ),
    ]
