# Generated by Django 6.0.2 on 2026-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='birth_certificate',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Свидетельство о рождении'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='pin',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='ПИН (паспорт, 14 цифр)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='access_code',
            field=models.CharField(blank=True, default='', help_text='Если пусто — код не требуется. Сообщите устно в аудитории.', max_length=30, verbose_name='Код доступа для студентов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
